# Generated by Django 5.2.6 on 2025-09-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Drive_Axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Streer_Axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_machine_number', models.CharField(max_length=500, unique=True)),
                ('number_engine', models.CharField(max_length=500)),
                ('number_transmission', models.CharField(max_length=500)),
                ('number_drive_axle', models.CharField(max_length=500)),
                ('number_steer_axle', models.CharField(max_length=500)),
                ('number_supply_contract', models.CharField(max_length=500)),
                ('date_shipment_with_factory', models.DateTimeField(auto_now_add=True)),
                ('cargo_recipient', models.CharField(max_length=500)),
                ('delivery_address', models.CharField(max_length=1000)),
                ('configuration', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=500)),
                ('model_drive_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_drive_axle', to='service.model_drive_axle')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_engine', to='service.model_engine')),
                ('model_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_model', to='service.model_machine')),
                ('model_steer_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_drive_axle', to='service.model_streer_axle')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_transmission', to='service.model_transmission')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines_by_service', to='service.service_company')),
            ],
        ),
    ]
