# Generated by Django 5.2.6 on 2025-09-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MethodRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelStreerAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_machine_number', models.CharField(max_length=500, unique=True)),
                ('number_engine', models.CharField(max_length=500)),
                ('number_transmission', models.CharField(max_length=500)),
                ('number_drive_axle', models.CharField(max_length=500)),
                ('number_steer_axle', models.CharField(max_length=500)),
                ('number_supply_contract', models.CharField(max_length=500)),
                ('date_shipment_with_factory', models.DateTimeField(auto_now_add=True)),
                ('cargo_recipient', models.CharField(max_length=500)),
                ('delivery_address', models.CharField(max_length=1000)),
                ('configuration', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=500)),
                ('model_drive_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modeldriveaxle')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelengine')),
                ('model_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelmachine')),
                ('model_steer_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelstreeraxle')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modeltransmission')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_failure', models.DateField()),
                ('running_hours', models.IntegerField(default=0)),
                ('description_failed', models.TextField()),
                ('spare_parts_usage', models.CharField(max_length=500)),
                ('date_restoration', models.DateField()),
                ('failed_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='service.failedunit')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='service.machine')),
                ('method_restoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='service.methodrestoration')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='service.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateField()),
                ('running_hours', models.IntegerField(default=0)),
                ('order', models.CharField(max_length=500)),
                ('date_order', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspections', to='service.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspections', to='service.servicecompany')),
                ('type_ti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspections', to='service.typeti')),
            ],
        ),
    ]
