# Generated by Django 5.2.6 on 2025-09-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelStreerAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_machine_number', models.CharField(max_length=500, unique=True)),
                ('number_engine', models.CharField(max_length=500)),
                ('number_transmission', models.CharField(max_length=500)),
                ('number_drive_axle', models.CharField(max_length=500)),
                ('number_steer_axle', models.CharField(max_length=500)),
                ('number_supply_contract', models.CharField(max_length=500)),
                ('date_shipment_with_factory', models.DateTimeField(auto_now_add=True)),
                ('cargo_recipient', models.CharField(max_length=500)),
                ('delivery_address', models.CharField(max_length=1000)),
                ('configuration', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=500)),
                ('model_drive_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modeldriveaxle')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelengine')),
                ('model_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelmachine')),
                ('model_steer_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modelstreeraxle')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.modeltransmission')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.servicecompany')),
            ],
        ),
    ]
