# Generated by Django 5.2.6 on 2025-09-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machine',
        ),
    ]
