# Generated by Django 5.2.6 on 2025-12-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelStreerAxle',
            new_name='ModelSteerAxle',
        ),
    ]
